import type { ProjectPhoto, ProjectState } from "../services/projectService";

export const DEMO_PROJECT_ID = "narrative-template-demo";
export const DEMO_PROJECT_NAME = "Narrative Demo";
export const DEMO_PROJECT_ROOT_PATH = "Narrative Demo Photos";

const DEFAULT_SETTINGS = {
  autoDay: true,
  folderStructure: {
    daysFolder: "01_DAYS",
    archiveFolder: "98_ARCHIVE",
    favoritesFolder: "FAV",
    metaFolder: "_meta",
  },
};

const photoList: ProjectPhoto[] = [
  {
    id: "OTHER-archive-ARCHIVE_IMG_20230830_05.jpg",
    originalName: "ARCHIVE_IMG_20230830_05.jpg",
    currentName: "ARCHIVE_IMG_20230830_05.jpg",
    timestamp: 1693396800000,
    day: null,
    bucket: "X",
    sequence: 1,
    favorite: false,
    rating: 0,
    archived: true,
    thumbnail: new URL(
      "../../../../template-photos/OTHER/archive/ARCHIVE_IMG_20230830_05.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "OTHER/archive/ARCHIVE_IMG_20230830_05.jpg",
    sourceFolder: "OTHER/archive",
    folderHierarchy: ["OTHER", "archive"],
    detectedDay: null,
    detectedBucket: "X",
    isPreOrganized: false,
    organizationConfidence: "low",
    subfolderOverride: null,
  },

  {
    id: "OTHER-archive-ARCHIVE_IMG_20230912_04.jpg",
    originalName: "ARCHIVE_IMG_20230912_04.jpg",
    currentName: "ARCHIVE_IMG_20230912_04.jpg",
    timestamp: 1694520000000,
    day: null,
    bucket: "X",
    sequence: 2,
    favorite: false,
    rating: 0,
    archived: true,
    thumbnail: new URL(
      "../../../../template-photos/OTHER/archive/ARCHIVE_IMG_20230912_04.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "OTHER/archive/ARCHIVE_IMG_20230912_04.jpg",
    sourceFolder: "OTHER/archive",
    folderHierarchy: ["OTHER", "archive"],
    detectedDay: null,
    detectedBucket: "X",
    isPreOrganized: false,
    organizationConfidence: "low",
    subfolderOverride: null,
  },

  {
    id: "OTHER-archive-ARCHIVE_IMG_20231005_03.jpg",
    originalName: "ARCHIVE_IMG_20231005_03.jpg",
    currentName: "ARCHIVE_IMG_20231005_03.jpg",
    timestamp: 1696507200000,
    day: null,
    bucket: "X",
    sequence: 3,
    favorite: false,
    rating: 0,
    archived: true,
    thumbnail: new URL(
      "../../../../template-photos/OTHER/archive/ARCHIVE_IMG_20231005_03.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "OTHER/archive/ARCHIVE_IMG_20231005_03.jpg",
    sourceFolder: "OTHER/archive",
    folderHierarchy: ["OTHER", "archive"],
    detectedDay: null,
    detectedBucket: "X",
    isPreOrganized: false,
    organizationConfidence: "low",
    subfolderOverride: null,
  },

  {
    id: "OTHER-archive-ARCHIVE_IMG_20231120_02.jpg",
    originalName: "ARCHIVE_IMG_20231120_02.jpg",
    currentName: "ARCHIVE_IMG_20231120_02.jpg",
    timestamp: 1700481600000,
    day: null,
    bucket: "X",
    sequence: 4,
    favorite: false,
    rating: 0,
    archived: true,
    thumbnail: new URL(
      "../../../../template-photos/OTHER/archive/ARCHIVE_IMG_20231120_02.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "OTHER/archive/ARCHIVE_IMG_20231120_02.jpg",
    sourceFolder: "OTHER/archive",
    folderHierarchy: ["OTHER", "archive"],
    detectedDay: null,
    detectedBucket: "X",
    isPreOrganized: false,
    organizationConfidence: "low",
    subfolderOverride: null,
  },

  {
    id: "OTHER-archive-ARCHIVE_IMG_20231215_01.jpg",
    originalName: "ARCHIVE_IMG_20231215_01.jpg",
    currentName: "ARCHIVE_IMG_20231215_01.jpg",
    timestamp: 1702641600000,
    day: null,
    bucket: "X",
    sequence: 5,
    favorite: false,
    rating: 0,
    archived: true,
    thumbnail: new URL(
      "../../../../template-photos/OTHER/archive/ARCHIVE_IMG_20231215_01.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "OTHER/archive/ARCHIVE_IMG_20231215_01.jpg",
    sourceFolder: "OTHER/archive",
    folderHierarchy: ["OTHER", "archive"],
    detectedDay: null,
    detectedBucket: "X",
    isPreOrganized: false,
    organizationConfidence: "low",
    subfolderOverride: null,
  },

  {
    id: "OTHER-misc_001.jpg",
    originalName: "misc_001.jpg",
    currentName: "misc_001.jpg",
    timestamp: 1705240800000,
    day: null,
    bucket: null,
    sequence: 1,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/OTHER/misc_001.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "OTHER/misc_001.jpg",
    sourceFolder: "OTHER",
    folderHierarchy: ["OTHER"],
    detectedDay: null,
    detectedBucket: null,
    isPreOrganized: false,
    organizationConfidence: "low",
    subfolderOverride: null,
  },

  {
    id: "OTHER-misc_002.jpg",
    originalName: "misc_002.jpg",
    currentName: "misc_002.jpg",
    timestamp: 1705244400000,
    day: null,
    bucket: null,
    sequence: 2,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/OTHER/misc_002.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "OTHER/misc_002.jpg",
    sourceFolder: "OTHER",
    folderHierarchy: ["OTHER"],
    detectedDay: null,
    detectedBucket: null,
    isPreOrganized: false,
    organizationConfidence: "low",
    subfolderOverride: null,
  },

  {
    id: "OTHER-misc_003.jpg",
    originalName: "misc_003.jpg",
    currentName: "misc_003.jpg",
    timestamp: 1705248000000,
    day: null,
    bucket: null,
    sequence: 3,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/OTHER/misc_003.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "OTHER/misc_003.jpg",
    sourceFolder: "OTHER",
    folderHierarchy: ["OTHER"],
    detectedDay: null,
    detectedBucket: null,
    isPreOrganized: false,
    organizationConfidence: "low",
    subfolderOverride: null,
  },

  {
    id: "OTHER-misc_004.jpg",
    originalName: "misc_004.jpg",
    currentName: "misc_004.jpg",
    timestamp: 1705251600000,
    day: null,
    bucket: null,
    sequence: 4,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/OTHER/misc_004.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "OTHER/misc_004.jpg",
    sourceFolder: "OTHER",
    folderHierarchy: ["OTHER"],
    detectedDay: null,
    detectedBucket: null,
    isPreOrganized: false,
    organizationConfidence: "low",
    subfolderOverride: null,
  },

  {
    id: "Day 1-action.jpg",
    originalName: "action.jpg",
    currentName: "action.jpg",
    timestamp: 1770051024647,
    day: 1,
    bucket: null,
    sequence: 1,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/Day 1/action.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "Day 1/action.jpg",
    sourceFolder: "Day 1",
    folderHierarchy: ["Day 1"],
    detectedDay: 1,
    detectedBucket: null,
    isPreOrganized: false,
    organizationConfidence: "low",
    subfolderOverride: null,
  },

  {
    id: "Day 1-detail.jpg",
    originalName: "detail.jpg",
    currentName: "detail.jpg",
    timestamp: 1770051024654,
    day: 1,
    bucket: null,
    sequence: 2,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/Day 1/detail.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "Day 1/detail.jpg",
    sourceFolder: "Day 1",
    folderHierarchy: ["Day 1"],
    detectedDay: 1,
    detectedBucket: null,
    isPreOrganized: false,
    organizationConfidence: "low",
    subfolderOverride: null,
  },

  {
    id: "Day 1-detail_2.jpg",
    originalName: "detail_2.jpg",
    currentName: "detail_2.jpg",
    timestamp: 1770051024659,
    day: 1,
    bucket: null,
    sequence: 3,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/Day 1/detail_2.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "Day 1/detail_2.jpg",
    sourceFolder: "Day 1",
    folderHierarchy: ["Day 1"],
    detectedDay: 1,
    detectedBucket: null,
    isPreOrganized: false,
    organizationConfidence: "low",
    subfolderOverride: null,
  },

  {
    id: "Day 1-food.jpg",
    originalName: "food.jpg",
    currentName: "food.jpg",
    timestamp: 1770051024664,
    day: 1,
    bucket: null,
    sequence: 4,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/Day 1/food.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "Day 1/food.jpg",
    sourceFolder: "Day 1",
    folderHierarchy: ["Day 1"],
    detectedDay: 1,
    detectedBucket: null,
    isPreOrganized: false,
    organizationConfidence: "low",
    subfolderOverride: null,
  },

  {
    id: "Day 1-food_2.jpg",
    originalName: "food_2.jpg",
    currentName: "food_2.jpg",
    timestamp: 1770051024670,
    day: 1,
    bucket: null,
    sequence: 5,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/Day 1/food_2.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "Day 1/food_2.jpg",
    sourceFolder: "Day 1",
    folderHierarchy: ["Day 1"],
    detectedDay: 1,
    detectedBucket: null,
    isPreOrganized: false,
    organizationConfidence: "low",
    subfolderOverride: null,
  },

  {
    id: "Day 1-people.jpg",
    originalName: "people.jpg",
    currentName: "people.jpg",
    timestamp: 1770051024676,
    day: 1,
    bucket: null,
    sequence: 6,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/Day 1/people.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "Day 1/people.jpg",
    sourceFolder: "Day 1",
    folderHierarchy: ["Day 1"],
    detectedDay: 1,
    detectedBucket: null,
    isPreOrganized: false,
    organizationConfidence: "low",
    subfolderOverride: null,
  },

  {
    id: "Day 1-transition.jpg",
    originalName: "transition.jpg",
    currentName: "transition.jpg",
    timestamp: 1770051024682,
    day: 1,
    bucket: null,
    sequence: 7,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/Day 1/transition.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "Day 1/transition.jpg",
    sourceFolder: "Day 1",
    folderHierarchy: ["Day 1"],
    detectedDay: 1,
    detectedBucket: null,
    isPreOrganized: false,
    organizationConfidence: "low",
    subfolderOverride: null,
  },

  {
    id: "Day 2-action.jpg",
    originalName: "action.jpg",
    currentName: "action.jpg",
    timestamp: 1770051024686,
    day: 2,
    bucket: "D",
    sequence: 1,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/Day 2/action.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "Day 2/action.jpg",
    sourceFolder: "Day 2",
    folderHierarchy: ["Day 2"],
    detectedDay: 2,
    detectedBucket: "D",
    isPreOrganized: true,
    organizationConfidence: "high",
    subfolderOverride: null,
  },

  {
    id: "Day 2-detail.jpg",
    originalName: "detail.jpg",
    currentName: "detail.jpg",
    timestamp: 1770051024692,
    day: 2,
    bucket: "C",
    sequence: 2,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/Day 2/detail.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "Day 2/detail.jpg",
    sourceFolder: "Day 2",
    folderHierarchy: ["Day 2"],
    detectedDay: 2,
    detectedBucket: "C",
    isPreOrganized: true,
    organizationConfidence: "high",
    subfolderOverride: null,
  },

  {
    id: "Day 2-detail_2.jpg",
    originalName: "detail_2.jpg",
    currentName: "detail_2.jpg",
    timestamp: 1770051024696,
    day: 2,
    bucket: "C",
    sequence: 3,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/Day 2/detail_2.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "Day 2/detail_2.jpg",
    sourceFolder: "Day 2",
    folderHierarchy: ["Day 2"],
    detectedDay: 2,
    detectedBucket: "C",
    isPreOrganized: true,
    organizationConfidence: "high",
    subfolderOverride: null,
  },

  {
    id: "Day 2-food.jpg",
    originalName: "food.jpg",
    currentName: "food.jpg",
    timestamp: 1770051024700,
    day: 2,
    bucket: "M",
    sequence: 4,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/Day 2/food.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "Day 2/food.jpg",
    sourceFolder: "Day 2",
    folderHierarchy: ["Day 2"],
    detectedDay: 2,
    detectedBucket: "M",
    isPreOrganized: true,
    organizationConfidence: "high",
    subfolderOverride: null,
  },

  {
    id: "Day 2-food_2.jpg",
    originalName: "food_2.jpg",
    currentName: "food_2.jpg",
    timestamp: 1770051024704,
    day: 2,
    bucket: "M",
    sequence: 5,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/Day 2/food_2.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "Day 2/food_2.jpg",
    sourceFolder: "Day 2",
    folderHierarchy: ["Day 2"],
    detectedDay: 2,
    detectedBucket: "M",
    isPreOrganized: true,
    organizationConfidence: "high",
    subfolderOverride: null,
  },

  {
    id: "Day 2-people.jpg",
    originalName: "people.jpg",
    currentName: "people.jpg",
    timestamp: 1770051024709,
    day: 2,
    bucket: "B",
    sequence: 6,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/Day 2/people.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "Day 2/people.jpg",
    sourceFolder: "Day 2",
    folderHierarchy: ["Day 2"],
    detectedDay: 2,
    detectedBucket: "B",
    isPreOrganized: true,
    organizationConfidence: "high",
    subfolderOverride: null,
  },

  {
    id: "Day 2-transition.jpg",
    originalName: "transition.jpg",
    currentName: "transition.jpg",
    timestamp: 1770051024715,
    day: 2,
    bucket: "E",
    sequence: 7,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/Day 2/transition.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "Day 2/transition.jpg",
    sourceFolder: "Day 2",
    folderHierarchy: ["Day 2"],
    detectedDay: 2,
    detectedBucket: "E",
    isPreOrganized: true,
    organizationConfidence: "high",
    subfolderOverride: null,
  },

  {
    id: "Day 3-action.jpg",
    originalName: "action.jpg",
    currentName: "action.jpg",
    timestamp: 1770051024719,
    day: 3,
    bucket: "D",
    sequence: 1,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/Day 3/action.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "Day 3/action.jpg",
    sourceFolder: "Day 3",
    folderHierarchy: ["Day 3"],
    detectedDay: 3,
    detectedBucket: "D",
    isPreOrganized: true,
    organizationConfidence: "high",
    subfolderOverride: null,
  },

  {
    id: "Day 3-detail.jpg",
    originalName: "detail.jpg",
    currentName: "detail.jpg",
    timestamp: 1770051024725,
    day: 3,
    bucket: "C",
    sequence: 2,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/Day 3/detail.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "Day 3/detail.jpg",
    sourceFolder: "Day 3",
    folderHierarchy: ["Day 3"],
    detectedDay: 3,
    detectedBucket: "C",
    isPreOrganized: true,
    organizationConfidence: "high",
    subfolderOverride: null,
  },

  {
    id: "Day 3-detail_2.jpg",
    originalName: "detail_2.jpg",
    currentName: "detail_2.jpg",
    timestamp: 1770051024729,
    day: 3,
    bucket: null,
    sequence: 3,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/Day 3/detail_2.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "Day 3/detail_2.jpg",
    sourceFolder: "Day 3",
    folderHierarchy: ["Day 3"],
    detectedDay: 3,
    detectedBucket: null,
    isPreOrganized: false,
    organizationConfidence: "low",
    subfolderOverride: null,
  },

  {
    id: "Day 3-food.jpg",
    originalName: "food.jpg",
    currentName: "food.jpg",
    timestamp: 1770051024734,
    day: 3,
    bucket: "M",
    sequence: 4,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/Day 3/food.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "Day 3/food.jpg",
    sourceFolder: "Day 3",
    folderHierarchy: ["Day 3"],
    detectedDay: 3,
    detectedBucket: "M",
    isPreOrganized: true,
    organizationConfidence: "high",
    subfolderOverride: null,
  },

  {
    id: "Day 3-food_2.jpg",
    originalName: "food_2.jpg",
    currentName: "food_2.jpg",
    timestamp: 1770051024739,
    day: 3,
    bucket: null,
    sequence: 5,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/Day 3/food_2.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "Day 3/food_2.jpg",
    sourceFolder: "Day 3",
    folderHierarchy: ["Day 3"],
    detectedDay: 3,
    detectedBucket: null,
    isPreOrganized: false,
    organizationConfidence: "low",
    subfolderOverride: null,
  },

  {
    id: "Day 3-people.jpg",
    originalName: "people.jpg",
    currentName: "people.jpg",
    timestamp: 1770051024744,
    day: 3,
    bucket: "B",
    sequence: 6,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/Day 3/people.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "Day 3/people.jpg",
    sourceFolder: "Day 3",
    folderHierarchy: ["Day 3"],
    detectedDay: 3,
    detectedBucket: "B",
    isPreOrganized: true,
    organizationConfidence: "high",
    subfolderOverride: null,
  },

  {
    id: "Day 3-transition.jpg",
    originalName: "transition.jpg",
    currentName: "transition.jpg",
    timestamp: 1770051024749,
    day: 3,
    bucket: null,
    sequence: 7,
    favorite: false,
    rating: 0,
    archived: false,
    thumbnail: new URL(
      "../../../../template-photos/Day 3/transition.jpg",
      import.meta.url
    ).href,
    mimeType: "image/jpeg",
    filePath: "Day 3/transition.jpg",
    sourceFolder: "Day 3",
    folderHierarchy: ["Day 3"],
    detectedDay: 3,
    detectedBucket: null,
    isPreOrganized: false,
    organizationConfidence: "low",
    subfolderOverride: null,
  },
];

export const demoProjectState: ProjectState = {
  projectName: DEMO_PROJECT_NAME,
  rootPath: DEMO_PROJECT_ROOT_PATH,
  settings: DEFAULT_SETTINGS,
  photos: photoList,
  dayLabels: {
    1: "Day 1",
    2: "Day 2",
    3: "Day 3",
  },
  dayContainers: [],
  lastModified: Date.now(),
};
